# Generated by Django 5.1.5 on 2025-09-01 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('total_emails', models.IntegerField(default=0)),
                ('job_applications_found', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_processing_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'E-posta İşlem Kaydı',
                'verbose_name_plural': 'E-posta İşlem Kayıtları',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_scan_days', models.PositiveIntegerField(default=5, help_text='E-posta tarama için geri gidilecek gün sayısı (1-365)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='E-posta Tarama Günü')),
                ('email_scan_limit', models.PositiveIntegerField(default=50000, help_text='Maksimum taranacak e-posta sayısı (100-500000)', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(500000)], verbose_name='E-posta Tarama Limiti')),
                ('email_batch_size', models.PositiveIntegerField(default=10, help_text='Batch işleme boyutu (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='E-posta Batch Boyutu')),
                ('gemini_api_key', models.CharField(blank=True, help_text='Gemini API anahtarı', max_length=500, verbose_name='Gemini API Anahtarı')),
                ('gemini_cache_ttl', models.PositiveIntegerField(default=60, help_text='Cache TTL dakika cinsinden (1-1440)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Gemini Cache TTL (Dakika)')),
                ('gmail_credentials', models.JSONField(blank=True, help_text='Gmail API için OAuth2 token bilgileri', null=True, verbose_name='Gmail API Kimlik Bilgileri')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sistem Ayarları',
                'verbose_name_plural': 'Sistem Ayarları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profili')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Profili')),
                ('preferred_locations', models.CharField(blank=True, help_text='Virgülle ayırın: İstanbul, Ankara, İzmir', max_length=500, verbose_name='Tercih Edilen Şehirler')),
                ('preferred_positions', models.CharField(blank=True, help_text='Virgülle ayırın: Python Developer, Full Stack Developer', max_length=500, verbose_name='Tercih Edilen Pozisyonlar')),
                ('total_applications', models.PositiveIntegerField(default=0, verbose_name='Toplam Başvuru')),
                ('last_email_sync', models.DateTimeField(blank=True, null=True, verbose_name='Son E-posta Senkronizasyonu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Şirket Adı')),
                ('position', models.CharField(max_length=200, verbose_name='Pozisyon')),
                ('email_sender', models.EmailField(max_length=254, verbose_name='Gönderen E-posta')),
                ('application_date', models.DateTimeField(verbose_name='Başvuru Tarihi')),
                ('status', models.CharField(choices=[('received', 'Başvuru Alındı'), ('reviewing', 'İnceleniyor'), ('interview', 'Mülakat Aşaması'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('waiting', 'Geri Dönüş Bekleniyor')], default='received', max_length=20, verbose_name='Durum')),
                ('email_subject', models.CharField(max_length=300, verbose_name='E-posta Konusu')),
                ('email_content', models.TextField(verbose_name='E-posta İçeriği')),
                ('gmail_message_id', models.CharField(max_length=100, verbose_name='Gmail Mesaj ID')),
                ('extracted_info', models.JSONField(blank=True, null=True, verbose_name='Çıkarılan Bilgiler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İş Başvurusu',
                'verbose_name_plural': 'İş Başvuruları',
                'ordering': ['-application_date'],
                'unique_together': {('user', 'gmail_message_id')},
            },
        ),
    ]
