# Generated by Django 5.1.5 on 2025-09-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('received', 'Başvuru Alındı'), ('reviewing', 'Başvuru İnceleniyor'), ('interview', 'Mülakat Aşaması'), ('accepted', 'İş Başvurusu Kabul Edildi'), ('rejected', 'İş Başvurusu Reddedildi'), ('pending', 'İş Başvurusu Beklemede')], default='received', max_length=20, verbose_name='Durum'),
        ),
    ]
